### ISSUE TITLE
Arduino_USBHostMbed5 missing from requirements

### ISSUE THREAD

**Issue by toqduj** [arduino-libraries/Arduino_POSIXStorage#17]
Tiny issue, but this library was not automatically added..

**Comment by per1234** [comment]
Hi @toqduj. Please add a comment here to provide a detailed description of what method you used to install the "Arduino_POSIXStorage" library.

The dependency is indeed specified in the library metadata:

https://github.com/arduino-libraries/Arduino_POSIXStorage/blob/b29fb52f9d94b075b8ff638ec7e23427507cba54/library.properties#L9

and this caused the user to be prompted about installation of the dependency when using Arduino IDE Library Manager:

![image](https://github.com/arduino-libraries/Arduino_POSIXStorage/assets/8572152/6a5b7e49-70f3-4b14-ab8a-52ae2bad7946)

**Comment by toqduj** [comment]
Hm, interesting. I did remember seeing a message, but didn't remember which library it needed to install in addition. I always click "install all". This was in the Arduino IDE 2.3.1. But it could be I just misremembered or misclicked. Apologies if so.
